// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oskhweltnnifpzxahyij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9za2h3ZWx0bm5pZnB6eGFoeWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTE4MzksImV4cCI6MjA2NDkyNzgzOX0.FjfVWCVsykf43UztsD5s1fjTxKKVDTXg6mO_kHIq8Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);